// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[]           = "9c0e47d1-925d-4897-a87c-1ebe5b471734";
const char DEVICE_LOGIN_NAME[]  = "12d29afc-9e7d-4a66-bdcc-b95a0e55ecb0";

const char SSID[]               = SECRET_SSID;       // Network SSID (name)
const char PASS[]               = SECRET_PASS;       // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]         = SECRET_DEVICE_KEY; // Secret device password

void onAddRemovePetChange();
void onQuantityChange();
void onScheduleChange();

int add_remove_pet;
int quantity;
int schedule;
bool almost_empty;
bool error;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(add_remove_pet, READWRITE, ON_CHANGE, onAddRemovePetChange);
  ArduinoCloud.addProperty(quantity, READWRITE, ON_CHANGE, onQuantityChange);
  ArduinoCloud.addProperty(schedule, READWRITE, ON_CHANGE, onScheduleChange);
  ArduinoCloud.addProperty(almost_empty, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(error, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
